apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app-kustomization
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./cluster-resources/my-app
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: my-app-git-repo
  timeout: 3m0s
  wait: true
